kind: pipeline
type: docker
name: minimal-version

steps:
- name: test
  image: ubuntu:18.04
  commands:
  - apt-get update > /dev/null
  - apt-get install -y apt-utils > /dev/null
  # install non-python packages
  - apt-get install -y rcs > /dev/null
  - apt-get install -y subversion > /dev/null
  - apt-get install -y git > /dev/null
  - apt-get install -y libjs-mathjax > /dev/null
  # install python3 and the necessary python packages
  - apt-get install -y python3 > /dev/null
  - apt-get install -y python3-werkzeug > /dev/null
  - apt-get install -y python3-jinja2 > /dev/null
  - apt-get install -y python3-webtest > /dev/null
  # install tzdata without waiting for input, needed by python-epydoc
  - DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata > /dev/null
  - apt-get install -y python-epydoc > /dev/null
  # wsgitools is only available via pip
  - apt-get install -y python3-pip > /dev/null
  # TODO the only version of wsgitools which is available on pip is 0.3.1
  - python3 -m pip install --no-cache-dir wsgitools
  # finally, perform the tests
  - make check

trigger:
  event:
    exclude:
    - pull_request

---

kind: pipeline
type: docker
name: recent-python

steps:
- name: test
  image: python:latest
  commands:
  # install non-python dependencies
  - apt-get update > /dev/null
  - apt-get install -y rcs > /dev/null
  - apt-get install -y libjs-mathjax > /dev/null
  # install python packages
  - pip install --no-cache-dir -r requirements.txt
  - pip install --no-cache-dir coverage
  # perform the tests
  - make coverage

trigger:
  event:
    exclude:
    - pull_request

---

kind: pipeline
type: docker
name: ubuntu-20.04

steps:
- name: test
  image: ubuntu:20.04
  commands:
  - apt-get update > /dev/null
  - apt-get install -y apt-utils > /dev/null
  # install non-python packages
  - apt-get install -y rcs > /dev/null
  - apt-get install -y subversion > /dev/null
  - apt-get install -y git > /dev/null
  - apt-get install -y libjs-mathjax > /dev/null
  # install python3 and the necessary python packages
  - apt-get install -y python3 > /dev/null
  - apt-get install -y python3-werkzeug > /dev/null
  # install tzdata without waiting for input, needed by python3-jinja2
  - DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata > /dev/null
  - apt-get install -y python3-jinja2  > /dev/null
  - apt-get install -y python3-webtest > /dev/null
  # wsgitools is only available via pip
  - apt-get install -y python3-pip > /dev/null
  # TODO the only version of wsgitools which is available on pip is 0.3.1
  - python3 -m pip install --no-cache-dir wsgitools
  - python3 -m pip install --no-cache-dir epydoc
  # finally, perform the tests
  - make check

trigger:
  event:
    exclude:
    - pull_request
