kind: pipeline
type: docker
name: python-3.10

steps:
- name: test
  image: python:3.10
  commands:
  # install non-python dependencies
  - apt-get update
  - apt-get install -y rcs
  - apt-get install -y libjs-mathjax
  # install python packages
  - pip install --no-cache-dir -r requirements.txt
  - pip install --no-cache-dir coverage
  # perform the tests
  - make coverage

trigger:
  event:
    exclude:
    - pull_request
