kind: pipeline
type: docker
name: recent-python

steps:
- name: test
  image: python:latest
  commands:
  # install non-python dependencies
  - apt-get update > /dev/null
  - apt-get install -y rcs > /dev/null
  - apt-get install -y libjs-mathjax > /dev/null
  # install python packages
  - pip install --no-cache-dir -r requirements.txt
  - pip install --no-cache-dir coverage
  # perform the tests
  - make coverage

trigger:
  event:
    exclude:
    - pull_request
